server:
    http_listen_port: 9080
    grpc_listen_port: 0

positions:
    filename: /tmp/positions.yaml

clients:
    - url: https://<LOKI_SERVER_IP>:3100/loki/api/v1/push
      tls_config:
          insecure_skip_verify: false

scrape_configs:
    - job_name: system-logs
      static_configs:
          - targets:
                - localhost
            labels:
                job: varlogs
                __path__: /var/log/*log

    - job_name: docker-logs
      docker_sd_configs:
          - host: unix:///var/run/docker.sock
            refresh_interval: 10s
      relabel_configs:
          - source_labels: [__meta_docker_container_name]
            target_label: container
