server:
    http_listen_port: 9080
    grpc_listen_port: 0
    log_level: info

positions:
    filename: /tmp/positions.yaml

clients:
    - url: http://loki:3100/loki/api/v1/push

scrape_configs:
    # ---------------- System Logs ----------------
    - job_name: system-logs
      static_configs:
          - targets:
                - localhost
            labels:
                job: system
                host: ${HOSTNAME}
                __path__: /var/log/*.log

    # ---------------- Docker Logs ----------------
    - job_name: docker-logs
      docker_sd_configs:
          - host: unix:///var/run/docker.sock
            refresh_interval: 10s

      relabel_configs:
          - source_labels: [__meta_docker_container_name]
            target_label: container
          - source_labels: [__meta_docker_container_image]
            target_label: image
          - source_labels: [__meta_docker_container_label_com_docker_compose_service]
            target_label: compose_service
          - source_labels: [__meta_docker_container_label_com_docker_compose_project]
            target_label: project

      pipeline_stages:
          - docker: {} # parses docker log format automatically
          - drop:
                expression: '.*(healthcheck).*' # Delete unnecessary logs
          - multiline:
                firstline: '^\S' # multi-line support (example: Python Traceback)
