global:
    resolve_timeout: 5m

route:
    # Default route
    receiver: 'default-receiver'
    group_by: ['alertname', 'job']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h

receivers:
    - name: 'default-receiver'
      # Slack example (optional)
      # slack_configs:
      #   - api_url: 'https://hooks.slack.com/services/XXX/YYY/ZZZ'
      #     channel: '#alerts'

      # Email example (optional)
      # email_configs:
      #   - to: 'ops@example.com'
      #     from: 'alertmanager@example.com'
      #     smarthost: 'smtp.example.com:587'
      #     auth_username: 'alertmanager'
      #     auth_identity: 'alertmanager'
      #     auth_password: 'password'

inhibit_rules:
    - source_match:
          severity: critical
      target_match:
          severity: warning
      equal: ['alertname', 'job']
